info:
  model: int-scaffold
packages:
- gitBranch: main
  gitServerName: pooja
  gitUrl: https://github.com/Pooja-Anand-IBM-2
  gitUsername: Pooja-Anand-IBM-2
  name: ExternalPISRemovalProject
version: '1.0'
